metadata:
  name: Default
gainPriority:
  - card: Province
    condition: "my.coins >= 8"
  - card: Gold
    condition: "my.coins >= 6"
  - card: Silver
    condition: "my.coins >= 3"
  - card: Copper
    condition: "my.coins < 3"
discardPriority:
  - card: Colony
  - card: Province
  - card: Duchy
  - card: Estate
  - card: Curse
