"""Empires Landmarks."""

from .base_landmark import Landmark
from .registry import LANDMARK_TYPES, all_landmarks, get_landmark
from .landmarks import (
    Aqueduct,
    Arena,
    BanditFort,
    Basilica,
    Battlefield,
    Colonnade,
    DefiledShrine,
    Fountain,
    Keep,
    Labyrinth,
    MountainPass,
    Museum,
    Obelisk,
    Orchard,
    Palace,
    Tomb,
    Tower,
    TriumphalArch,
    Wall,
    WolfDen,
)

__all__ = [
    "Landmark",
    "LANDMARK_TYPES",
    "all_landmarks",
    "get_landmark",
    "Aqueduct",
    "Arena",
    "BanditFort",
    "Basilica",
    "Battlefield",
    "Colonnade",
    "DefiledShrine",
    "Fountain",
    "Keep",
    "Labyrinth",
    "MountainPass",
    "Museum",
    "Obelisk",
    "Orchard",
    "Palace",
    "Tomb",
    "Tower",
    "TriumphalArch",
    "Wall",
    "WolfDen",
]
