from typing import Type

from dominion.cards.base_card import Card
from dominion.cards.base_set import (
    Chapel,
    CouncilRoom,
    Festival,
    Laboratory,
    Market,
    Mine,
    Moat,
    Smithy,
    Village,
    Witch,
    Workshop,
)
from dominion.cards.expansions import (
    Archive,
    Beggar,
    BustlingVillage,
    Capital,
    Castle,
    Catapult,
    Charm,
    ChariotRace,
    Crown,
    Collection,
    Emporium,
    Encampment,
    Engineer,
    FarmersMarket,
    Forager,
    Forum,
    Fortune,
    Gladiator,
    Groundskeeper,
    Legionary,
    Miser,
    Modify,
    Overlord,
    Patrician,
    Plunder,
    Rats,
    Rebuild,
    Rocks,
    RoyalBlacksmith,
    Sacrifice,
    Settlers,
    Skulk,
    SnowyVillage,
    Temple,
    Villa,
    WildHunt,
    Crypt,
    Hovel,
    Necropolis,
    OvergrownEstate,
    Bank,
    Bishop,
    City,
    CityQuarter,
    Contraband,
    CountingHouse,
    Expand,
    Forge,
    Goons,
    GrandMarket,
    Hoard,
    KingsCourt,
    Loan,
    Mint,
    Monument,
    Mountebank,
    Peddler,
    Quarry,
    Rabble,
    RoyalSeal,
    Talisman,
    TradeRoute,
    Vault,
    Venture,
    Watchtower,
    WorkersVillage,
    Platinum,
    Colony,
    Amphora,
    Doubloons,
    EndlessChalice,
    Figurehead,
    Hammer,
    Insignia,
    Jewels,
    Orb,
    PrizeGoat,
    PuzzleBox,
    Sextant,
    Shield,
    SpellScroll,
    Staff,
    Sword,
    LOOT_CARD_NAMES,
)
from dominion.cards.hinterlands import Trail, Trader, Inn, Mill
from dominion.cards.renaissance import ActingTroupe
from dominion.cards.allies import Taskmaster
from dominion.cards.intrigue import Torturer, Patrol, Bridge, Nobles
from dominion.cards.plunder import FirstMate, Barbarian
from dominion.cards.dark_ages import Ironmonger, Marauder, Spoils, Ruins
from dominion.cards.adventures import Giant
from dominion.cards.nocturne import TragicHero
from dominion.cards.menagerie import Horse

from dominion.cards.treasures import Copper, Gold, Silver
from dominion.cards.victory import Curse, Duchy, Estate, Province

# Updated registry of all card types
CARD_TYPES: dict[str, Type[Card]] = {
    # Treasure cards
    "Copper": Copper,
    "Silver": Silver,
    "Gold": Gold,
    # Victory cards
    "Estate": Estate,
    "Duchy": Duchy,
    "Province": Province,
    "Curse": Curse,
    # Action cards
    "Village": Village,
    "Smithy": Smithy,
    "Market": Market,
    "Festival": Festival,
    "Laboratory": Laboratory,
    "Mine": Mine,
    "Witch": Witch,
    "Moat": Moat,
    "Workshop": Workshop,
    "Chapel": Chapel,
    "Council Room": CouncilRoom,
    # Expansion cards
    "Archive": Archive,
    "Bustling Village": BustlingVillage,
    "Capital": Capital,
    "Castle": Castle,
    "Catapult": Catapult,
    "Charm": Charm,
    "Chariot Race": ChariotRace,
    "Patrician": Patrician,
    "Emporium": Emporium,
    "Forager": Forager,
    "Snowy Village": SnowyVillage,
    "Miser": Miser,
    "Rats": Rats,
    "Skulk": Skulk,
    "Collection": Collection,
    "Beggar": Beggar,
    "Modify": Modify,
    "Rebuild": Rebuild,
    "Crypt": Crypt,
    "Hovel": Hovel,
    "Necropolis": Necropolis,
    "Overgrown Estate": OvergrownEstate,
    "Crown": Crown,
    "Encampment": Encampment,
    "Engineer": Engineer,
    "Farmers' Market": FarmersMarket,
    "Forum": Forum,
    "Fortune": Fortune,
    "Gladiator": Gladiator,
    "Bank": Bank,
    "Bishop": Bishop,
    "City": City,
    "City Quarter": CityQuarter,
    "Contraband": Contraband,
    "Counting House": CountingHouse,
    "Expand": Expand,
    "Forge": Forge,
    "Goons": Goons,
    "Grand Market": GrandMarket,
    "Hoard": Hoard,
    "King's Court": KingsCourt,
    "Loan": Loan,
    "Mint": Mint,
    "Monument": Monument,
    "Mountebank": Mountebank,
    "Overlord": Overlord,
    "Peddler": Peddler,
    "Quarry": Quarry,
    "Rabble": Rabble,
    "Rocks": Rocks,
    "Royal Seal": RoyalSeal,
    "Royal Blacksmith": RoyalBlacksmith,
    "Sacrifice": Sacrifice,
    "Settlers": Settlers,
    "Talisman": Talisman,
    "Temple": Temple,
    "Trade Route": TradeRoute,
    "Vault": Vault,
    "Venture": Venture,
    "Watchtower": Watchtower,
    "Workers' Village": WorkersVillage,
    "Villa": Villa,
    "Wild Hunt": WildHunt,
    "Legionary": Legionary,
    "Groundskeeper": Groundskeeper,
    "Plunder": Plunder,
    "Platinum": Platinum,
    "Colony": Colony,
    "Amphora": Amphora,
    "Doubloons": Doubloons,
    "Endless Chalice": EndlessChalice,
    "Figurehead": Figurehead,
    "Hammer": Hammer,
    "Insignia": Insignia,
    "Jewels": Jewels,
    "Orb": Orb,
    "Prize Goat": PrizeGoat,
    "Puzzle Box": PuzzleBox,
    "Sextant": Sextant,
    "Shield": Shield,
    "Spell Scroll": SpellScroll,
    "Staff": Staff,
    "Sword": Sword,
    "Trail": Trail,
    "Mill": Mill,
    "Acting Troupe": ActingTroupe,
    "Taskmaster": Taskmaster,
    "Trader": Trader,
    "Torturer": Torturer,
    "Patrol": Patrol,
    "Bridge": Bridge,
    "Nobles": Nobles,
    "Inn": Inn,
    "First Mate": FirstMate,
    "Barbarian": Barbarian,
    "Ironmonger": Ironmonger,
    "Marauder": Marauder,
    "Spoils": Spoils,
    "Ruins": Ruins,
    "Giant": Giant,
    "Tragic Hero": TragicHero,
    "Horse": Horse,
}


def get_card(name: str) -> Card:
    """Get a new instance of a card by name."""
    if name not in CARD_TYPES:
        raise ValueError(f"Unknown card: {name}")
    return CARD_TYPES[name]()
